server:
  port: 8080

weather:
  api:
    key: ${API_KEY}
    url: https://api.openweathermap.org/data/2.5
    ip-lookup-url: https://ipapi.co/json

spring:
  cache:
    type: caffeine
  caffeine:
    spec: maximumSize=100, expireAfterWrite=10m